class NameError < StandardError

  def self.exception(arg0, arg1, *rest)
  end

  def initialize(arg0, arg1, *rest)
  end

  def to_s
  end

  def name
  end

end
